print("\n===========Student's Profile==============")

name = input("Enter your name:")
student_id = input("Enter your student_id:")
age = input("Enter your age:")
mobile = input("Enter your valid mobile no:")
address = input("Enter valid address:")
state = input("Enter your state:")
country = input("ENter your country:")
email = input("Enter you email:")

print("\n===========Student's College Details=======")
college_name = input("Enter your college name:")
college_add = input("Enter college address:")
name = input("Enter your name:")
student_id = input("Enter your student_id:")
branch = input("Enter your branch:")
semester = input("Enter your present semester:")
cgpa = input("Enter cgpa:")

print("\n===========Student Detail's================")
print("Name = ",name)
print("Student_Id = ",student_id)
print("Branch = ",branch)
print("Semester = ",semester)
print("College_name = ",college_name)
print("College_address = ",college_add)
print("CGPA = ",cgpa)
print("State = ",state)
print("Country = ",country)
print("Mobile = ",mobile)
print("Email =",email)